baseURL = "https://psep.cl/"
languageCode = "es"
title = "Psep.cl"
theme = "hyde-hyde"

disqusShortname = "psepcl"

[params]
	postNavigation = true
	relatedPosts = true
	author = "Pablo Sepúlveda P."
	description = "Si es libre, es bueno."
	authorimage = "/img/gnu.png"
	copyright = "psep"
	license = "CC BY-SA 4.0"
	licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
	highlightjs = true
	highlightjsstyle = "github"
	themeColor = "theme-base-0p"
	Commento = true
	showBuiltWith = true

[params.meta]
	description = "Si es libre, es bueno."
	keywords = "software libre, free software, gnu, java, arquitectura, apache, camel, microservicios, soa, middleware, bpm, jboss, debian, linux, android, firefox, rust, mozilla"

[params.social]
	twitter = "psep_cl"
	github = "psep"
	keybase = "psep"
	linkedin = "pablopsep"
	email = "psep@protonmail.ch"
	lichess = "psep"

[[menu.main]]
	name = "Posts"
	identifier = "posts"
	weight = 100
	url = "/posts/"
[[menu.main]]
	name = "Acerca de"
	identifier = "acerca-de"
	weight = 200
	url = "/acerca-de/"

[[menu.planet]]
	name = "Proyecto GNU"
	identifier = "gnu project"
	weight = 200
	url = "https://gnu.org"
[[menu.planet]]
	name = "Mozilla Chile"
	identifier = "mozilla chile"
	weight = 200
	url = "http://mozillachile.cl"
[[menu.planet]]
	name = "Apache Camel"
	identifier = "apache camel"
	weight = 200
	url = "https://camel.apache.org/blog/"
